[package]
name = "timer_interval_trigger_synchronized"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-interval = "0.1.4"
