[package]
name = "tokio_process_command"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["process", "full"] }
